services:
  backend:
    build: ./streamwise-backend
    container_name: streamwise-backend
    ports:
      - "8080:8080"
    env_file:
      - ./streamwise-backend/.env
    networks:
      - streamwise-network

  frontend:
    build: ./streamwise-frontend
    container_name: streamwise-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - streamwise-network

networks:
  streamwise-network:
